### ISSUE TITLE
Ways to reduce GPU memory

### ISSUE THREAD

**Issue by lxxue** [autonomousvision/monosdf#14]
Hi, 

Thanks for the great work and for sharing the code. I met with a GPU OOM problem when training on the ScanNet / Replica dataset. I only have a 3060 available with 12GB memory. I checked the batch size in the configuration but it was set to 1 so I could not reduce it further. I wonder if there is any simple way to reduce memory usage so I can quickly run some experiments?

**Comment by niujinshuchong** [comment]
Hi, 12GB should be enough. I can run on 2080ti which also has 12GB memory. Which config file are you using?

**Comment by lxxue** [comment]
Thanks for the quick reply. I was using the `scannet_mlp.conf` and `replica_mlp.conf` when I met with the OOM error. I tested on `scannet_grids.conf` and it was OK (~10GB memory usage).

**Comment by cv-lab-x** [comment]
I met with the OOM erro when i use a large datasets with more than 3000 imgs,  how to train with large datasets to avoid OOM error ?
looking forward to your reply! thanks @niujinshuchong

**Comment by niujinshuchong** [comment]
@cv-lab-x We haven't try with more than 500 images? But I don't think 3k images will lead to OOM error because the images are stored in cpu memory.  Are you sure it's because of number of images? Could you reduce the number of images to confirm?

**Comment by cv-lab-x** [comment]
@niujinshuchong i got this error when i try more than 3k imgs, the code runs ok when i reduce to less than 400 imgs
x out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1659484810403/work/aten/src/ATen/native/cuda/IndexKernel.cu:91: operator(): block: [0,0,0], thread: [25,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1659484810403/work/aten/src/ATen/native/cuda/IndexKernel.cu:91: operator(): block: [0,0,0], thread: [26,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1659484810403/work/aten/src/ATen/native/cuda/IndexKernel.cu:91: operator(): block: [0,0,0], thread: [27,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1659484810403/work/aten/src/ATen/native/cuda/IndexKernel.cu:91: operator(): block: [0,0,0], thread: [28,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1659484810403/work/aten/src/ATen/native/cuda/IndexKernel.cu:91: operator(): block: [0,0,0], thread: [29,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1659484810403/work/aten/src/ATen/native/cuda/IndexKernel.cu:91: operator(): block: [0,0,0], thread: [30,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1659484810403/work/aten/src/ATen/native/cuda/IndexKernel.cu:91: operator(): block: [0,0,0], thread: [31,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
Traceback (most recent call last):
  File "training/exp_runner.py", line 71, in <module>
    trainrunner.run()
  File "/home/x00480977/projects/nvvps/monosdf/code/../code/training/monosdf_train.py", line 251, in run
    model_outputs = self.model(model_input, indices)
  File "/root/miniconda3/envs/monosdf/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/monosdf/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1008, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/root/miniconda3/envs/monosdf/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 969, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/root/miniconda3/envs/monosdf/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x00480977/projects/nvvps/monosdf/code/../code/model/network.py", line 454, in forward
    weights = self.volume_rendering(z_vals, sdf)
  File "/home/x00480977/projects/nvvps/monosdf/code/../code/model/network.py", line 515, in volume_rendering
    dists = torch.cat([dists, torch.tensor([1e10]).cuda().unsqueeze(0).repeat(dists.shape[0], 1)], -1)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 0 (pid: 5867) of binary: /root/miniconda3/envs/monosdf/bin/python
Traceback (most recent call last):
  File "/root/miniconda3/envs/monosdf/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/envs/monosdf/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/miniconda3/envs/monosdf/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/root/miniconda3/envs/monosdf/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/root/miniconda3/envs/monosdf/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/root/miniconda3/envs/monosdf/lib/python3.8/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/root/miniconda3/envs/monosdf/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/miniconda3/envs/monosdf/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
=====================================================
training/exp_runner.py FAILED
-----------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
-----------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-10-12_08:15:17
  host      : 347e81532b20
  rank      : 0 (local_rank: 0)
  exitcode  : -6 (pid: 5867)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 5867

**Comment by cv-lab-x** [comment]
@niujinshuchong hi, i got this error when i use large datasets, but it runs ok by reducing to less than 400 imgs
/opt/conda/conda-bld/pytorch_1659484810403/work/aten/src/ATen/native/cuda/IndexKernel.cu:91: operator(): block: [0,0,0], thread: [31,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
Traceback (most recent call last):
  File "training/exp_runner.py", line 71, in <module>
    trainrunner.run()
  File "../code/training/monosdf_train.py", line 251, in run
    model_outputs = self.model(model_input, indices)
  File "/root/miniconda3/envs/monosdf/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/monosdf/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1008, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/root/miniconda3/envs/monosdf/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 969, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/root/miniconda3/envs/monosdf/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "../code/model/network.py", line 454, in forward
    weights = self.volume_rendering(z_vals, sdf)
  File "../code/model/network.py", line 515, in volume_rendering
    dists = torch.cat([dists, torch.tensor([1e10]).cuda().unsqueeze(0).repeat(dists.shape[0], 1)], -1)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by niujinshuchong** [comment]
@cv-lab-x Could you update this line to use more images?
https://github.com/autonomousvision/monosdf/blob/main/code/model/network.py#L348

**Comment by cv-lab-x** [comment]
> @cv-lab-x Could you update this line to use more images? https://github.com/autonomousvision/monosdf/blob/main/code/model/network.py#L348

it works, the self.embeddings means transients embedding or appearance embedding ? @niujinshuchong

**Comment by niujinshuchong** [comment]
@cv-lab-x It's the appearance embedding.
