### ISSUE TITLE
AttributeError: 'MonoSDFTrainRunner' object has no attribute 'checkpoints_path'

### ISSUE THREAD

**Issue by bobfacer** [autonomousvision/monosdf#29]
It seems that there is something wrong in the multi-GPU process when I run the code. It exits in 660 epochs when I run scannet 4 dataset, and it exits in 300 epochs when I run scannet 1 dataset.

```
scannet_mlp_4_2022_10_21_21_02_11 [660] (302/303): loss = 0.08707078546285629, rgb_loss = 0.03575834631919861, eikonal_loss = 0.014714548364281654, psnr = 23.60033416748047, bete=0.0009753454942256212, alpha=1025.2777153535253
Traceback (most recent call last):
  File "training/exp_runner.py", line 71, in <module>
    trainrunner.run()
  File "/data/niuzy/Python/monosdf/code/../code/training/monosdf_train.py", line 288, in run
    self.save_checkpoints(epoch)
  File "/data/niuzy/Python/monosdf/code/../code/training/monosdf_train.py", line 170, in save_checkpoints
    os.path.join(self.checkpoints_path, self.model_params_subdir, str(epoch) + ".pth"))
AttributeError: 'MonoSDFTrainRunner' object has no attribute 'checkpoints_path'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 656559) of binary: /data/niuzy/anaconda3/envs/monosdf/bin/python
Traceback (most recent call last):
  File "/data/niuzy/anaconda3/envs/monosdf/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/niuzy/anaconda3/envs/monosdf/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/niuzy/anaconda3/envs/monosdf/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/data/niuzy/anaconda3/envs/monosdf/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/data/niuzy/anaconda3/envs/monosdf/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/data/niuzy/anaconda3/envs/monosdf/lib/python3.8/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/data/niuzy/anaconda3/envs/monosdf/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/data/niuzy/anaconda3/envs/monosdf/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
training/exp_runner.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-10-22_11:35:19
  host      : amax
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 656559)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

```

**Comment by niujinshuchong** [comment]
Hi, thanks for reporting this. Hope it's fixed with the latest commint https://github.com/autonomousvision/monosdf/commit/8e46ed516c80c30b73043ff163c2bd94b4b67062.
